import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../sass/pages/Home.module.scss";
import useTranslation from "next-translate/useTranslation";

const Home: NextPage = () => {
  const { t } = useTranslation("home");

  return (
    <div className={styles.container}>
      <Head>
        <title>CBT - Cool Blind Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            height: 500,
            width: 500,
            backgroundColor: "red",
            borderRadius: "50%",
          }}
        ></div>

        <div className={styles.buttons}>
          <Link href="/signup">
            <a className={styles.inscription}>{t("signUp")}</a>
          </Link>
          <Link href="/signin">
            <a className={styles.connexion}>{t("signIn")}</a>
          </Link>
          <Link href="/play">
            <a className={styles.anonyme}>{t("anon")}</a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
